#!/bin/bash
# 
# Author: chris.jenkins@oracle.com
# 
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
# 
# LICENSE UPL 1.0
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# 
# Script to display the container's logs.
# 

declare -r cfgfilename="container.cfg"
declare -r dflt_containername="ttcontainer"

declare basedir
declare cfgfile
declare follow=""
declare -i ret=0

usage()
{
    echo
    echo "Usage:"
    echo
    echo "    ttlog [-f|--follow]"
    echo
    echo "Displays the docker log for the TimesTen container. If '--follow'"
    echo "is specified, displays new log data as it is generated. Interrupt"
    echo "with 'Ctrl-C'."
    echo
    exit 100
}

loadConfig()
{
    local cfile

    if [[ $# -ne 1 ]]
    then
        return 1
    fi
    cfile="$1"

    if ! source "${cfile}" >& /dev/null
    then
        echo
        echo "error: unable to load configuration from '${cfile}'"
        echo
        return 1
    fi
    if [[ "${DOCKER_TTCONTAINER}" == "" ]]
    then
        export DOCKER_TTCONTAINER="${dflt_containername}"
    fi

    return 0
}

if [[ $# -gt 1 ]]
then
    usage
elif [[ $# -eq 1 ]]
then
    if [[ "$1" == "-f" ]] || [[ "$1" == "--follow" ]]
    then
        follow="-f"
    else
        usage
    fi
fi

basedir=$(dirname "$0")
cfgfile="${basedir}/${cfgfilename}"
if ! loadConfig "${cfgfile}"
then
    exit 1
fi

docker logs ${follow} "${DOCKER_TTCONTAINER}"
ret=$?

exit ${ret}
